### PR TITLE
base64 too heavy for gmail signature, replacing with absolute URLs 

### PR DESCRIPTION
**Pull request by edelans**
dirty trick for the moment : icons are hosted on github issues, #dirty trick : https://stackoverflow.com/a/32252663/1570104

waiting for more suitable image hosting https://trello.com/c/N02QILc9/458-problem-in-our-signature-wt-gmail-app-dark-mode#comment-5ee741ada71c985813331188

@FabriceGaudin

### CODE REVIEW

**Comment by FabriceGaudin** [comment]
@edelans Thanks! If hosting images on Marketo is quick to do, I'd rather wait for this clean solution. If not we would need to update signatures using that old trick.

**Comment by edelans** [comment]
@FabriceGaudin done !

**Review by FabriceGaudin — APPROVED** [review]
Looks good! Thanks, I let you merge

**Comment by edelans** [comment]
@FabriceGaudin I can't I don't have write access.

image

**Comment by FabriceGaudin** [comment]
@edelans My bad, it's merged!
I let you ping Maria?

**Comment by edelans** [comment]
@FabriceGaudin ok i test and ping Maria ;)

Tx for your help !

**Comment by FabriceGaudin** [comment]
@edelans There's a problem I think. Images seem not to load (https://360learning.github.io/signatureGenerator.html) : 
image

**Comment by edelans** [comment]
@FabriceGaudin 

I've just checked and it does work for me now I whitelisted the marketo domain in my adblocker :  

image


do you use an ad blocker ?  😏

**Comment by edelans** [comment]
(c'est sans fin ce truc !)

**Comment by FabriceGaudin** [comment]
@edelans I use Adblock but even if I disable it, icons aren't displayed in Firefox. Same thing with private window in Firefox...
However this works in Chrome. Let's test with Maria, maybe it's only me due to some weird configurations...

**Comment by edelans** [comment]
@FabriceGaudin actually, I experience troubles as well. Not in the https://360learning.github.io/signatureGenerator.html, but in the gmail signature settings : 

image


But it's weird because it does it to me after whitelisting the marketo url on my 2 ad blockers (dns + extension), with emptied cache. If i click on the URL of the images I can reach them, but I get 404'ed in the gmail signature... 


It's commence à faire beaucoup. Maybe we should consider (yet) another hosting.

**Comment by FabriceGaudin** [comment]
@edelans Can you try to replace the link with `https` instead of `http` in your signature?

**Comment by edelans** [comment]
@FabriceGaudin 

good catch !! 


But still no luck : 

image


it looks like Google adds a display:none to the element with a marketo url (the display:none is not in the source html that I copy to the gmail signature...)

**Comment by FabriceGaudin** [comment]
@edelans Ok, let's host our assets elsewhere...
Actually I think we can simply host them on this repo and load them with something like https://360learning.github.io/assets/facebook.png for instance.

**Comment by edelans** [comment]
@FabriceGaudin I openned another PR for this fix.

**Comment by edelans** [comment]
#2

**Pull request merged**
